########################################################################
# Values section defines the parameters to the chart
# These are specific to the chart being installed
########################################################################

imagePullSecret: regcred
image:
  repository: container-registry.dev8.bip.va.gov/blue/bip-reference-person
  tag: latest
  pullPolicy: Always
ingress:
  enabled: false
vault:
  enabled: false
  consulBackendEnabled: false
consul:
    enabled: false
    config:
      enabled: false
    discovery:
      enabled: false
      register: false
spring:
  profiles: "dev,ci"
opa:
  enabled: true
bip:
  framework:
    localstack:
      enabled: false