INSERT INTO PERSON_DOCS (ID, PID, DOC_NAME, DOC_CREATE_DATE) VALUES(NEXTVAL('SEQ'), 6666345, '', NULL) ON CONFLICT (ID) DO UPDATE SET (PID, DOC_NAME, DOC_CREATE_DATE) = (6666345, '', NULL);
INSERT INTO PERSON_DOCS (ID, PID, DOC_NAME, DOC_CREATE_DATE) VALUES(NEXTVAL('SEQ'), 6666346, 'dname', NULL) ON CONFLICT (ID) DO UPDATE SET (PID, DOC_NAME, DOC_CREATE_DATE) = (6666346, 'dname', NULL);
