--CREATE TABLE PERSONRECORD (PID INT PRIMARY KEY, DOCUMENT BLOB);

INSERT INTO PERSONRECORD (ID, PID, DOCUMENT) VALUES(1, 6666345, '');
INSERT INTO PERSONRECORD (ID, PID, DOCUMENT) VALUES(2, 6666346, '');
