INSERT INTO PERSONRECORD (ID, PID, DOCUMENT_NAME, DOCUMENT_CREATION_DATE) VALUES(1, 6666345, '', NULL);
INSERT INTO PERSONRECORD (ID, PID, DOCUMENT_NAME, DOCUMENT_CREATION_DATE) VALUES(2, 6666346, 'dname', NULL);
