CREATE TABLE IF NOT EXISTS PERSON_DOCS (
    ID   INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    DOC_NAME VARCHAR(128),
    DOC_CREATE_DATE VARCHAR(128),
    PRIMARY KEY (id)
);
GRANT ALL PRIVILEGES ON PERSON_DOCS TO postgres;