CREATE TABLE IF NOT EXISTS PERSONRECORD (
    ID   INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    DOCUMENT_NAME VARCHAR(128),
    DOCUMENT_CREATION_DATE VARCHAR(128),
    PRIMARY KEY (id)
);
GRANT ALL PRIVILEGES ON PERSONRECORD TO postgres;